name: Website Monitoring

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check website availability
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://assetengineers.com.au)
          if [ "$response" != "200" ]; then
            echo "Website is not responding correctly. Status code: $response"
            exit 1
          fi
          echo "Website is up and running. Status code: $response"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Website Monitoring Alert',
              body: 'The website monitoring check failed. Please investigate the website status.'
            }) 